#Must use ABICALLS by setting NORMAL_APP, the ld.sys will call the dynamic entry with t9 as base on MIPS
NORMAL_APP=yes

include $(MY_BUILD_BASE)/config.mk

PARTS = fnotify tcpip multipi

all: subs_parts

include $(MY_BUILD_BASE)/cc.mk

 
